name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - name: Install tmate
        run: sudo apt update && sudo apt install tmate -y

      - name: Start tmate
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "SSH: $(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')"
          echo "WEB: $(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')"
          sleep 21600
